# Generated by Django 4.1 on 2024-01-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuneTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='artists'),
        ),
        migrations.AddField(
            model_name='song',
            name='album_cover',
            field=models.ImageField(blank=True, upload_to='songs'),
        ),
    ]
