# Generated by Django 4.1 on 2024-01-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuneTracker', '0002_artist_profile_pic_song_album_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
